sidebar:
  sidebar_free_text:
    default: "<b>Free Text</b>"
    client: true
  sidebar_overwrite_template:
    default: true
    client: false
  sidebar_widgets:
    default: stats|medium|facebook_page
    client: true
  sidebar_fb_page:
    default: ""
    client: true
  sidebar_forum_news_category:
    default: ""
    client: true