uncategorized:
  sidebar_overwrite_template:
    default: true
    client: false
  sidebar_widgets:
    default: stats|medium|facebook_page
    client: true
  sidebar_fb_page:
    default: ""
    client: true